name: Deploy Homestay App

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install flake8
      - run: flake8 . --max-line-length=120 --exclude=venv,__pycache__,instance --ignore=E302,E303,E501,W503,F401,E711,W291,E128,E126,E127,E121,E122,E123,E124,E125,E131,E261,E262,E265,E266,W292,W293,W391
